### ISSUE TITLE
Magnet Card upgrade from ae2wtlib no longer works

### ISSUE THREAD

**Issue by TrustiDx** [starforcraft/AE2-Insert-Export-Card#2]
Nice that the upgrades now also work in the Universal Wireless Terminal!

Unfortunately the magnet card upgrade for the wireless/universal terminal no longer works with this mod installed, would be great if you could use both. 

Forge 47.2.20
ae2insertexportcard-1.20.1-1.1.1
ae2wtlib-15.2.2-forge

Thank you!

**Comment by starforcraft** [comment]
Singeplayer or Multiplayer?

**Comment by starforcraft** [comment]
https://github.com/Mari023/AE2WirelessTerminalLibrary/pull/254

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals/files/5217955
