### ISSUE TITLE
The latest version 1.1.2 broke the JEI - AE2 sync feature again. 

### ISSUE THREAD

**Issue by mentimjojo** [starforcraft/AE2-Insert-Export-Card#3]
As the title describes, the latest update of this mod breaks the search sync feature between AE2 terminals and JEI again.

This issue is the same as an earlier issue here which was fixed in a previous version. 
https://github.com/starforcraft/AE2-Insert-Export-Card/issues/1

When using version 1.1.1 the search sync feature works, but not on 1.1.2
https://imgur.com/a/syqcTlk

**Comment by starforcraft** [comment]
https://github.com/starforcraft/AE2-Insert-Export-Card/commit/29c0fa0107a58f6648cd1327ced6cca5841295c1 https://legacy.curseforge.com/minecraft/mc-mods/ae2-insert-export-card/files/5222015

**Comment by starforcraft** [comment]
Sorry for this stupid mistake, my IQ is in the single digits lol
