### ISSUE TITLE
 the item is deleted if there is no place in the ME system

### ISSUE THREAD

**Issue by FriendlyCube** [starforcraft/AE2-Insert-Export-Card#4]
if there is not enough space in the me system and I want to use the insert card, then the item will be deleted

as you can see, I have closed all types in the storage cell
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/e5d9e458-ac1a-4e74-8bda-dc3a41cf5d15)

next, I set up the insert card for slot 9
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/288cf0ed-13b1-4486-b7d5-c49824da88d2)

checking for the absence of a green block
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/f38df675-109e-40d5-a3a0-3479d03c0898)

I put the green block in the configured slot
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/f959229c-409f-4a18-8df7-75deeb1a902c)

the block disappears
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/4174ed44-67dc-49e3-9df2-19b0ec572643)

now I am checking the me system for the absence of this block
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/5aaab8b1-f6ed-4e2b-adf1-8417e4f21244)

result:
the item has been deleted and this is a bug, I hope you can fix this unpleasant bug

additionally: 
this bug will work even if there is no storage cell in the me system
![image](https://github.com/starforcraft/AE2-Insert-Export-Card/assets/112543401/04ac23bb-dc47-467c-a8a2-109c77ee6679)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ae2-insert-export-card/files/5224093

**Comment by FriendlyCube** [comment]
thx
