### ISSUE TITLE
[extension] Crafting Card

### ISSUE THREAD

**Issue by DeadPsych** [starforcraft/AE2-Insert-Export-Card#5]
Hi,

I have some suggestions as to what else could be added to the mod as an extension to the export card. These would be the following:

"Crafting Card" - Works like the exporter in AE2
If the item that is exported to the inventory is no longer available in the AE2 system but can be crafted, this will also be done.

Thank you for your work!

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ae2-insert-export-card/files/5412588
