### ISSUE TITLE
[Suggestion] Add ability to drag items from your inventory slots into the filters.

### ISSUE THREAD

**Issue by Kevin-Marsh** [starforcraft/AE2-Insert-Export-Card#6]
I am playing around with the mod and it seems like not being able to drag from your inventory to set the filters limits the ability to do certain things. Dragging from your inventory would allow you to set filters with exact nbt that would provide for more flexibility. Maybe clicking the slot would set the slot activation and click and drag would be able to take it up to the filter?

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ae2-insert-export-card/files/5412588
